name: example
description: Sample app for bottom_nav_layout package.
publish_to: 'none'
version: 1.1.1
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  bottom_nav_layout:
    git:
      url: https://github.com/m-azyoksul/bottom_nav_layout.git
      ref: main

  # Dependencies for different bottom bar designs
  salomon_bottom_bar: ^3.1.0
  bottom_bar_with_sheet: ^1.1.1
  animated_bottom_navigation_bar: ^0.3.2
  water_drop_nav_bar: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
