name: bottom_nav_layout
description: A quick and powerful app layout. Supports page state preservation, lazy page loading, and has a page backstack.
version: 1.1.1
homepage: https://github.com/m-azyoksul/bottom_nav_layout

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # Dependencies for different bottom bar designs
  flutter_snake_navigationbar: ^0.5.0
  salomon_bottom_bar: ^3.1.0
  bottom_bar_with_sheet: ^1.1.1
  animated_bottom_navigation_bar: ^0.3.2
  water_drop_nav_bar: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
