name: bottom_nav_layout
description: A quick layout with bottom navigation, tab back stack, and  state management.
version: 0.0.1
homepage: https://github.com/m-azyoksul/bottom_nav_layout

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
